export const INITIAL_GAME_STATE = 'INITIAL_GAME_STATE';
export const SLOT_INTERACTION = 'SLOT_INTERACTION';
export const PERFORM_MOVE = 'PERFORM_MOVE';
export const MOVE_CARD_EXCHANGE = 'MOVE_CARD_EXCHANGE';
export const AUTO_MOVE_CARD_EXCHANGE = 'AUTO_MOVE_CARD_EXCHANGE';